# Version.cmake - Generate version header from project version

set(THREATONE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(THREATONE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(THREATONE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(THREATONE_VERSION_STRING "${PROJECT_VERSION}")

# Generate version header
set(VERSION_HEADER_DIR "${CMAKE_BINARY_DIR}/generated/include")
file(MAKE_DIRECTORY "${VERSION_HEADER_DIR}/threatone")

file(WRITE "${VERSION_HEADER_DIR}/threatone/version.h"
"#pragma once

// Auto-generated by CMake - do not edit manually

#define THREATONE_VERSION_MAJOR ${THREATONE_VERSION_MAJOR}
#define THREATONE_VERSION_MINOR ${THREATONE_VERSION_MINOR}
#define THREATONE_VERSION_PATCH ${THREATONE_VERSION_PATCH}
#define THREATONE_VERSION_STRING \"${THREATONE_VERSION_STRING}\"

namespace ThreatOne {

struct Version {
    static constexpr int major = ${THREATONE_VERSION_MAJOR};
    static constexpr int minor = ${THREATONE_VERSION_MINOR};
    static constexpr int patch = ${THREATONE_VERSION_PATCH};
    static constexpr const char* string = \"${THREATONE_VERSION_STRING}\";
};

} // namespace ThreatOne
")

# Make the generated header available
add_library(threatone_version INTERFACE)
target_include_directories(threatone_version INTERFACE "${VERSION_HEADER_DIR}")
