#pragma once

// ThreatOne Database Model - Alert
// Represents system alerts generated by detection engines.

#include <string>
#include <vector>
#include <database/Model.h>

namespace ThreatOne::Database::Models {

class Alert : public Model<Alert> {
public:
    static constexpr const char* tableName() { return "alerts"; }

    static std::vector<FieldMeta> fields() {
        return {
            {"id", FieldType::Integer, false, true},
            {"type", FieldType::Text, false, false},
            {"severity", FieldType::Text, false, false},
            {"source", FieldType::Text, true, false},
            {"message", FieldType::Text, false, false},
            {"acknowledged", FieldType::Boolean, false, false},
            {"created_at", FieldType::Timestamp, false, false}
        };
    }

    void fromRow(const Row& row);
    [[nodiscard]] std::vector<std::pair<std::string, BoundParam>> toParams() const;
    [[nodiscard]] nlohmann::json toJson() const;
    void fromJson(const nlohmann::json& j);

    [[nodiscard]] const std::string& type() const { return type_; }
    void setType(const std::string& val) { type_ = val; }

    [[nodiscard]] const std::string& severity() const { return severity_; }
    void setSeverity(const std::string& val) { severity_ = val; }

    [[nodiscard]] const std::string& source() const { return source_; }
    void setSource(const std::string& val) { source_ = val; }

    [[nodiscard]] const std::string& message() const { return message_; }
    void setMessage(const std::string& val) { message_ = val; }

    [[nodiscard]] bool acknowledged() const { return acknowledged_; }
    void setAcknowledged(bool val) { acknowledged_ = val; }

    [[nodiscard]] const std::string& createdAt() const { return createdAt_; }
    void setCreatedAt(const std::string& val) { createdAt_ = val; }

private:
    std::string type_;
    std::string severity_ = "info";
    std::string source_;
    std::string message_;
    bool acknowledged_ = false;
    std::string createdAt_;
};

} // namespace ThreatOne::Database::Models
